name: Richard Johannisson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5d8cf'
    - '#060000'
    - '#655754'
    - '#a79485'
    - '#6c2314'
  brandStrength: 1
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.12314996868371964
purpose: []
